from faultTreeContinuous import Event, Gate, FaultTree

# BAD GENERATION!!!!!!!!!!
top_event = Event("Top Event")
and1 = Gate("AND", parent=top_event)
intermediate_event_1 = Event("Intermediate Event 1", parent=and1)
intermediate_event_3 = Event("Intermediate Event 3", parent=and1)
and2 = Gate("AND", parent=intermediate_event_1)
intermediate_event_2 = Event("Intermediate Event 2", parent=and2)
intermediate_event_7 = Event("Intermediate Event 7", parent=and2)
null3 = Gate("NULL", parent=intermediate_event_2)
intermediate_event_4 = Event("Intermediate Event 4", parent=null3)
basic_event_1 = Event("Basic Event 1", parent=null3)
basic_event_2 = Event("Basic Event 2", parent=null3)
null4 = Gate("NULL", parent=intermediate_event_3)
intermediate_event_4 = Event("Intermediate Event 4", parent=null4)
intermediate_event_5 = Event("Intermediate Event 5", parent=null4)
or5 = Gate("OR", parent=intermediate_event_4)
intermediate_event_6 = Event("Intermediate Event 6", parent=or5)
basic_event_4 = Event("Basic Event 4", parent=or5)
or6 = Gate("OR", parent=intermediate_event_5)
intermediate_event_6 = Event("Intermediate Event 6", parent=or6)
basic_event_5 = Event("Basic Event 5", parent=or6)
and7 = Gate("AND", parent=intermediate_event_6)
basic_event_6 = Event("Basic Event 6", parent=and7)
basic_event_7 = Event("Basic Event 7", parent=and7)
basic_event_8 = Event("Basic Event 8", parent=and7)
null8 = Gate("NULL", parent=intermediate_event_7)
basic_event_1 = Event("Basic Event 1", parent=null8)
basic_event_2 = Event("Basic Event 2", parent=null8)
basic_event_3 = Event("Basic Event 3", parent=null8)

fault_tree = FaultTree(top_event)
fault_tree.print_tree()
